import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { ensureWorkspace, exists, readJson, writeJson } from "../core/workspace.js";
import type { CheckResult, IntegrationGraph, Inventory } from "../core/types.js";
import { engagementPath, loadEngagement } from "../core/engagement.js";
import { buildGraph, renderMermaid } from "../core/graph.js";
import { scanRepository } from "../scanners/repo.js";
import { runDefaultChecks } from "../checks/defaultChecks.js";
import { annotateFindingsWithLearnings, loadLearnings } from "../core/learnings.js";
import { VERSION } from "../version.js";

// `fde export context` bundles everything a coding agent needs about the
// engagement into one Markdown file (for context windows) and one JSON file
// (for programmatic use): engagement, inventory, graph, findings.

export interface ContextBundle {
  generatedAt: string;
  generator: string;
  engagement: unknown;
  engagementYaml: string | null;
  inventory: Inventory;
  graph: IntegrationGraph;
  checkResult: CheckResult;
}

async function gather(root: string): Promise<ContextBundle> {
  const engagement = await loadEngagement(root);
  const engagementFile = engagementPath(root);
  const engagementYaml = (await exists(engagementFile)) ? await readFile(engagementFile, "utf8") : null;

  // Prefer the scan artifact when present; otherwise scan in memory.
  const invPath = path.join(root, ".fde", "environment", "inventory.json");
  const inventory = (await exists(invPath)) ? await readJson<Inventory>(invPath) : await scanRepository(root);

  const graph = buildGraph(inventory, engagement, root);
  const checkResult = annotateFindingsWithLearnings(
    await runDefaultChecks(inventory, engagement),
    await loadLearnings(root)
  );

  return {
    generatedAt: new Date().toISOString(),
    generator: `openfde ${VERSION}`,
    engagement,
    engagementYaml,
    inventory,
    graph,
    checkResult
  };
}

function renderContextMarkdown(bundle: ContextBundle): string {
  const { inventory, checkResult } = bundle;
  const critical = checkResult.findings.filter((f) => f.severity === "critical");
  const other = checkResult.findings.filter((f) => f.severity !== "critical");

  const findingBlock = (findings: typeof checkResult.findings) =>
    findings
      .map(
        (f) =>
          `- **${f.title}** (${f.severity}, \`${f.id}\`)\n  ${f.explanation}\n${(f.evidence ?? [])
            .map((e) => `  - evidence: ${e}`)
            .join("\n")}${f.recommendation ? `\n  - recommendation: ${f.recommendation}` : ""}`
      )
      .join("\n") || "None.";

  return `# Engagement Context Bundle

Generated by ${bundle.generator} at ${bundle.generatedAt}. This file gives a
coding agent the full deployment context of this engagement. Respect the
declared constraints below — they are customer commitments, not suggestions.

## Engagement declaration (fde.yaml)

${bundle.engagementYaml ? `\`\`\`yaml\n${bundle.engagementYaml.trimEnd()}\n\`\`\`` : "No fde.yaml present — run `fde init`."}

## Detected environment

${inventory.components.map((c) => `- **${c.name}** (${c.category}) — evidence: ${c.evidence.slice(0, 3).join(", ")}`).join("\n") || "No components detected."}

## Integration graph

\`\`\`mermaid
${renderMermaid(bundle.graph).trimEnd()}
\`\`\`

## Preflight findings (overall ${checkResult.overallScore}/100)

### Critical — do not deploy past these

${findingBlock(critical)}

### Warnings

${findingBlock(other)}

## Standing rules for agents working in this repository

1. Do not widen any \`read_only\` boundary or add side-effecting behavior
   without an entry in \`spec.constraints.humanApproval.requiredFor\`.
2. Keep data inside the declared residency regions.
3. Never commit credentials; OpenFDE's secrets check runs in CI.
4. Update \`fde.yaml\` when integrations change — it is the contract the
   preflight validates.
`;
}

export async function exportCommand(root: string, target: string): Promise<void> {
  if (target !== "context") {
    throw new Error(`Unknown export target "${target}" (supported: context).`);
  }
  const ws = await ensureWorkspace(root);
  const bundle = await gather(root);

  const jsonPath = path.join(ws, "context.json");
  const mdPath = path.join(ws, "context.md");
  await writeJson(jsonPath, bundle);
  await writeFile(mdPath, renderContextMarkdown(bundle), "utf8");

  console.log("Exported engagement context bundle:");
  console.log(`  ${mdPath}   (paste into Claude Code / Cursor / Codex)`);
  console.log(`  ${jsonPath} (programmatic)`);
}
